### ISSUE TITLE
Does not work on Ubuntu 16.10

### ISSUE THREAD

**Issue by Hurtak** [sindresorhus/clipboard-cli#1]
Hi,

clipboard-cli does not seem to work on Ubuntu

- I installed with `npm install --global clipboard-cli`
- versions
  - os: `Ubuntu 16.04.1 LTS`
  - node: `v7.2.0`
  - npm: `3.10.9`

```
hurtak@dell-latitude:~$ echo "hello" | clipboard 
hurtak@dell-latitude:~$ clipboard 
null
```

**Comment by Hurtak** [comment]
I tried on different Ubuntu computer (Ubuntu 16.10, node 7.2.0) and there is the same problem.

**Comment by Hurtak** [comment]
Oh, I see, in clipboard readme there is a note about installing xsel on linux. I will make pull prequest to add this note to this repo readme.

**Comment by sindresorhus** [comment]
It should have thrown a nice error informing you to install `xsel`, but it was buggy: https://github.com/sindresorhus/clipboardy/commit/82acb3b7d362098a454db95a1e1fbf2dc6d940c5
