### ISSUE TITLE
Having issues running `clipboard help`

### ISSUE THREAD

**Issue by brianzhou13** [sindresorhus/clipboard-cli#4]
<img width="1066" alt="screen shot 2018-04-29 at 5 50 20 pm" src="https://user-images.githubusercontent.com/5092263/39411320-df10ed58-4bd5-11e8-9445-9d2c41b2989f.png">

I followed the install instructions, and I'm running node v8.11.1

**Comment by banyudu** [comment]
@brianzhou13 Are you running clipboard inside tmux or something similar?

I have the same issue in node v8.9.1, but only occurs in tmux. Not in normal terminal

**Comment by banyudu** [comment]
This error occurs in execa, seems have nothing to do with this repo.

**Comment by brianzhou13** [comment]
@banyudu yes -- I am running it inside of tmux. I didn't try it with normal terminal...

**Comment by sindresorhus** [comment]
I cannot reproduce this.
