### ISSUE TITLE
Self-Contained Executables

### ISSUE THREAD

**Issue by 4lch4** [sindresorhus/clipboard-cli#6]
Hey folks! I'm new to this repository, but I'm a huge fan of this tool and would love to help improve it where I can.

Personally, I think the next step for this tool is to have self-contained executables that could be installed via Chocolatey, Brew, etc. I [forked the repo][0] and did some testing on my end and I've not had any issues with the built executables.

I'd be more than happy to continue this work and set up distribution via Chocolatey, Brew, etc., I just don't wanna do this if there's no interest so I figured I'd ask before continuing forward :) 

[0]: https://github.com/4lch4/clipboard-cli

**Comment by sindresorhus** [comment]
There's no interest on my side, sorry. I don't want to deal with all these different package managers. You are of course free to submit it to these package managers as long as I don't have to deal with any support for it.

**Comment by 4lch4** [comment]
It'd be a bit of a pain to do from the repo if I'm not the owner as I'm not the most familiar. Would you mind if I used my fork as the base for distribution and just kept up-to-date with any changes you push?
